/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Laurie' at '12/05/16 16:14' with Gradle 2.13
 *
 * @author Laurie, @date 12/05/16 16:14
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
